site_name: ""
docs_dir: .

theme:
  features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
  name: material
  logo: images/logo.png
  palette:
    - scheme: default
      primary: '#2AACE2'
      accent: '#FAA81C'
    - scheme: slate
      primary: '#182A54'
      accent: '#2AACE2'


extra_css:
  - custom-code/extra.css

extra_javascript:
  - custom-code/extra.js
  - custom-code/version-lang-switch.js


markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Release notes: release-notes.md
  - FCC Essentials:
      - Overzicht: index.md
  - Apps:
      - Apps overzicht: apps/index.md
      - General: apps/general.md
      - Principal Toolbox: apps/principal-toolbox.md
      - Start: apps/start.md
      - Strategy: apps/strategy.md
      - Insights: apps/insights.md
      - Portfolio:
          - Portfolio homepage: apps/portfolio/portfolio-homepage.md
          - Portfolio app in general: apps/portfolio/portfolio-app-in-general.md
          - Overview: apps/portfolio/overview.md
          - Dashboard: apps/portfolio/dashboard.md
          - Portfolio Objectives: apps/portfolio/portfolio-objectives.md
          - Funnel: apps/portfolio/funnel.md
          - Balancing: apps/portfolio/balancing.md
          - Milestone planning: apps/portfolio/milestone-planning.md
          - Skill capacity planning: apps/portfolio/skill-capacity-planning.md
          - Capacity planning: apps/portfolio/capacity-planning.md
          - Financial Planning: apps/portfolio/financial-planning.md
          - Financial grid: apps/portfolio/financial-grid.md
          - Workflows: apps/portfolio/workflows.md
          - Key Results Tracking: apps/portfolio/key-results-tracking.md
          - Reporting: apps/portfolio/reporting.md
          - Issues: apps/portfolio/issues.md
          - Risks: apps/portfolio/risks.md
          - Documents: apps/portfolio/documents.md
      - Project: apps/project.md
      - Hours: apps/hours.md
      - BI Connectivity: apps/bi-connectivity.md
      - Azure DevOps connectivity: apps/azure-devops-connectivity.md
      - On premise: apps/on-premise.md
      - Agile program: apps/agile-program.md
      - Teams: apps/teams.md
      - Approval workflows: apps/approval-workflows.md
      - Jira connectivity: apps/jira-connectivity.md
      - Import / Export: apps/import---export.md
extra:
  generator: false
