name: Build & Deploy Multi-version Docs

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mkdocs-material
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material

      # ---------- SYMLINK FIX-STEP HIER TUSSENVOEGEN ----------
      - name: Fix symlinks for CI (custom-code, images)
        run: |
          for V in 20 19 18; do
            for L in nl en de; do
              # custom-code
              if [ -L "docs/$V/$L/custom-code" ]; then
                rm docs/$V/$L/custom-code
                cp -r docs/20/nl/custom-code docs/$V/$L/custom-code
              fi
              # images
              if [ -L "docs/$V/$L/images" ]; then
                rm docs/$V/$L/images
                cp -r docs/20/nl/images docs/$V/$L/images
              fi
            done
          done

      - name: Build all versions & languages
        run: |
          VERSIONS="20 19 18"
          LANGS="nl en de"
          for V in $VERSIONS; do
            for L in $LANGS; do
              if [ -f docs/$V/$L/mkdocs.yml ]; then
                echo "Build: $V/$L"
                mkdocs build -f docs/$V/$L/mkdocs.yml -d $(pwd)/site/$V/$L
              fi
            done
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
