name: Build & Deploy Multi-version Docs

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mkdocs-material en awesome-pages
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material mkdocs-awesome-pages-plugin

      - name: Copy shared custom-code and images to all versions/languages
        run: |
          VERSIONS="20 19 18"
          LANGS="nl en de"
          for V in $VERSIONS; do
            for L in $LANGS; do
              rm -rf docs/$V/$L/custom-code
              rm -rf docs/$V/$L/images
              cp -r custom-code docs/$V/$L/
              cp -r images docs/$V/$L/
            done
          done

      - name: Build all versions & languages
        run: |
          VERSIONS="20 19 18"
          LANGS="nl en de"
          for V in $VERSIONS; do
            for L in $LANGS; do
              if [ -f docs/$V/$L/mkdocs.yml ]; then
                echo "Build: $V/$L"
                mkdocs build -f docs/$V/$L/mkdocs.yml -d $(pwd)/site/$V/$L
              fi
            done
          done

      # ---- DIT IS DE NIEUWE STAP VOOR REDIRECT ----
      - name: Add root redirect index.html
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
            <meta http-equiv="refresh" content="0; url=/fortes-kb/20/nl/">
            <script>
              window.location.replace("/fortes-kb/20/nl/");
            </script>
            <title>Redirecting…</title>
          </head>
          <body>
            <p>Redirecting to the latest documentation…</p>
          </body>
          </html>' > site/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
